# Generated by Django 4.2.1 on 2023-05-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10)),
                ('v_type', models.IntegerField()),
                ('v_model', models.CharField(max_length=50)),
                ('c_des', models.CharField(max_length=500)),
            ],
        ),
    ]
