# Generated by Django 4.2.1 on 2023-05-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='c_des',
            new_name='vehicledes',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='v_model',
            new_name='vehiclemodel',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='v_type',
            new_name='vehicletype',
        ),
    ]
